### ISSUE TITLE
Enhancements to transaction history

### ISSUE THREAD

**Issue by tjanez** [Esya/oasis-wallet#81]
Send transaction:
![Txn history - 1 - Send](https://user-images.githubusercontent.com/2518544/119343219-704ad200-bc96-11eb-8cd0-e78ff94ce335.png)

Delegate transaction:
![Txn history - 2 - Delegate](https://user-images.githubusercontent.com/2518544/119343315-8e183700-bc96-11eb-9bc9-5c106e3049d6.png)

- I would suggest renaming the title to:
  - "Delegated 99,999.0 TEST"
- I would suggest renaming "Validator" to "To" and showing a validator's name instead of account address if the address is for a known validator with an entity in metadata registry. The validator's name could be a link to a page with more info about it (link to block explorer?) or to go under "Active delegation" tabs for that validator?
- Should the validator's avator also be shown somewhere?

Undelegate transaction:
![Txn history - 3 - Undelegate](https://user-images.githubusercontent.com/2518544/119343998-6d041600-bc97-11eb-90ba-cc890d97fbd0.png)

- Same suggestions as for the Delegate transaction.

**Comment by Esya** [comment]
Splitting this into two separate issues and closing this one : 

#89 - I'll change `Validator` and `To` to `Account` to avoid misleading issues 
#90 - This will be further down the line as there are multiple possible implementations for this (possibly actually fetching the metadata registry myself instead of relying on the explorer)
